config/routes.rb
Rails.application.routes.draw do
  resources :user
  resources :votes
  resources :people
  resources :openings

  get 'welcome/index'

  root 'welcome#index'
  match '/terms' => 'welcome#terms', via: [:get]
  match '/about' => 'welcome#about', via: [:get]
  match '/result' => 'welcome#result', via: [:get]
  match '/contact' => 'welcome#contact', via: [:get]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'moderator/index'
  get 'moderator/:id/ok' => 'moderator#make_ok', as: :make_ok
  get 'moderator/:id/reject' => 'moderator#make_reject', as: :make_reject
  get 'moderator/:id/new' => 'moderator#make_new', as: :make_new
  get 'moderator/users' => 'moderator#users', as: :users

  get ':encoded_name' => 'people#show_by_name', as: :person_by_name

end

app/controllers/moderator_controller.rb
class ModeratorController < ApplicationController
  before_action :set_person, only: [:make_ok, :make_reject, :make_new]
  before_action :check_moderator!

  def index
    @people = Person.all.order(created_at: :desc)
  end

  def users
    @users = User.all.order(created_at: :desc)
  end

  def make_ok
    @person.status = 'ok'
    @person.save
    redirect_to '/moderator/index'
  end

  def make_reject
    @person.status = 'rej'
    @person.save
    redirect_to '/moderator/index'
  end

  def make_new
    @person.status = 'new'
    @person.save
    redirect_to '/moderator/index'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

end

app/views/moderator/index.html.erb
<h1>Propuneri</h1>

<table class="table moderator_datatable">
  <thead>
  <tr>
    <th>Propus de</th>
    <th>Nume</th>
    <th>Propus la data</th>
    <th>Status</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @people.each do |person| %>
      <tr>
        <td><%= person.user.name %></td>
        <td>
          <img src="<%= person.picture_url %>" width="40" height="40" />
          <%= person.name %>
        </td>
        <td><%= person.created_at %></td>
        <td><%= person.status %></td>
        <td>
          <a href="<%= person_path :id => person.id %>">view</a> |
          <a href="<%= edit_person_path :id => person.id %>">edit</a> |
          <a href="<%= make_ok_path :id => person.id %>">ok</a> |
          <a href="<%= make_reject_path :id => person.id %>">rej</a> |
          <a href="<%= make_new_path :id => person.id %>">new</a> |
          <%= link_to 'delete', person, method: :delete, data: {confirm: 'Esti sigur ca il stergi de tot? Nu vrei doar sa ii dai reject?'}  %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/moderator/users.html.erb
<h1>Utilizatori</h1>

<table class="table moderator_datatable">
  <thead>
  <tr>
    <th>Nume</th>
    <th>Creat la</th>
    <th>Moderator</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.created_at %></td>
        <td><%= user.moderator %></td>
        <td>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>