config/routes.rb
Rails.application.routes.draw do
  resources :user
  resources :votes
  resources :people
  resources :openings

  get 'welcome/index'

  root 'welcome#index'
  match '/terms' => 'welcome#terms', via: [:get]
  match '/about' => 'welcome#about', via: [:get]
  match '/result' => 'welcome#result', via: [:get]
  match '/contact' => 'welcome#contact', via: [:get]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'moderator/index'
  get 'moderator/:id/ok' => 'moderator#make_ok', as: :make_ok
  get 'moderator/:id/reject' => 'moderator#make_reject', as: :make_reject
  get 'moderator/:id/new' => 'moderator#make_new', as: :make_new
  get 'moderator/users' => 'moderator#users', as: :users

  get ':encoded_name' => 'people#show_by_name', as: :person_by_name

end

app/models/opening.rb
class Opening < ActiveRecord::Base
  has_and_belongs_to_many :people
  before_create :initialize_inferred_fields
  has_many :votes

  protected
  def initialize_inferred_fields
    self.encoded_name = self.name
  end
end

app/controllers/openings_controller.rb
class OpeningsController < ModeratorController
  before_action :set_opening, only: [:show, :edit, :update, :destroy]
  before_action :check_moderator!

  # GET /openings
  # GET /openings.json
  def index
    @openings = Opening.all
  end

  # GET /openings/1
  # GET /openings/1.json
  def show
  end

  # GET /openings/new
  def new
    @opening = Opening.new
  end

  # GET /openings/1/edit
  def edit
  end

  # POST /openings
  # POST /openings.json
  def create
    @opening = Opening.new(opening_params)

    respond_to do |format|
      if @opening.save
        format.html { redirect_to @opening, notice: 'Opening was successfully created.' }
        format.json { render :show, status: :created, location: @opening }
      else
        format.html { render :new }
        format.json { render json: @opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /openings/1
  # PATCH/PUT /openings/1.json
  def update
    respond_to do |format|
      if @opening.update(opening_params)
        format.html { redirect_to @opening, notice: 'Opening was successfully updated.' }
        format.json { render :show, status: :ok, location: @opening }
      else
        format.html { render :edit }
        format.json { render json: @opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /openings/1
  # DELETE /openings/1.json
  def destroy
    @opening.destroy
    respond_to do |format|
      format.html { redirect_to openings_url, notice: 'Opening was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opening
      @opening = Opening.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opening_params
      params.require(:opening).permit(:name)
    end
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/views/openings/_form.html.erb
<%= form_for(@opening) do |f| %>
  <% if @opening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@opening.errors.count, "error") %> prohibited this opening from being saved:</h2>

      <ul>
      <% @opening.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
      <div class="field">
          <%= f.text_field :name, :placeholder => 'Numele pozitiei' %>
      </div>
    <%= f.submit %>
  </div>
<% end %>

app/views/openings/edit.html.erb
<h1>Editing Opening</h1>
<div id="content">
    <div class="container">
        <div class="row">
            <div class="span12">
                <%= render 'form' %>

                <%= link_to 'Show', @opening %> |
                <%= link_to 'Back', openings_path %>

            </div>
        </div>
    </div>
</div>

app/views/openings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Openings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @openings.each do |opening| %>
      <tr>
        <td><%= opening.name %></td>
        <td><%= link_to 'Show', opening %></td>
        <td><%= link_to 'Edit', edit_opening_path(opening) %></td>
        <td><%= link_to 'Destroy', opening, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Opening', new_opening_path %>

app/views/openings/new.html.erb
<h1>New Opening</h1>
<div id="content">
    <div class="container">
        <div class="row">
            <div class="span12">
                <%= render 'form' %>

                <%= link_to 'Back', openings_path %>

            </div>
        </div>
    </div>
</div>

app/views/openings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_opening_path(@opening) %> |
<%= link_to 'Back', openings_path %>