config/routes.rb
Rails.application.routes.draw do
  resources :user
  resources :votes
  resources :people
  resources :openings

  get 'welcome/index'

  root 'welcome#index'
  match '/terms' => 'welcome#terms', via: [:get]
  match '/about' => 'welcome#about', via: [:get]
  match '/result' => 'welcome#result', via: [:get]
  match '/contact' => 'welcome#contact', via: [:get]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'moderator/index'
  get 'moderator/:id/ok' => 'moderator#make_ok', as: :make_ok
  get 'moderator/:id/reject' => 'moderator#make_reject', as: :make_reject
  get 'moderator/:id/new' => 'moderator#make_new', as: :make_new
  get 'moderator/users' => 'moderator#users', as: :users

  get ':encoded_name' => 'people#show_by_name', as: :person_by_name

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
  <title>propun&#9679;pe</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<p class="notice"><%= notice %></p>

<p class="alert"><%= alert %></p>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-primary btn-dropnav" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">propun&#9679;pe</a>

      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <li class="
            <% if controller.controller_name == "people" && controller.action_name == "new" %>active
          <% end %>"><a href="<%= new_person_path %>">PROPUNE</a></li>
          <li class="
            <% if controller.controller_name == "people" && controller.action_name == "index" %>active
          <% end %>"><a href="<%= people_path %>">LIDERI</a></li>
          <li class="
            <% if controller.controller_name == "welcome" && controller.action_name == "terms" %>active
          <% end %>"><a href="<%= terms_path %>">CONDITII</a></li>
          <li class="
            <% if controller.controller_name == "welcome" && controller.action_name == "about" %>active
          <% end %>"><a href="<%= about_path %>">NOI</a></li>
          <li class="
            <% if controller.controller_name == "welcome" && controller.action_name == "contact" %>active
          <% end %>"><a href="<%= contact_path %>">CONTACT</a></li>
          <li>
            <% if user_signed_in? %>
                <%= link_to "log out", destroy_user_session_path, :method => :delete %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<%= yield %>

<div class="container">
  <div class="row  navbar navbar-collapse">
    <div class="span12">
      <ul class="nav pull-right">
        <% if user_signed_in? and current_user.moderator? %>
        <li><a href="<%= moderator_index_path %>">moderator</a> </li>
        <% end %>
        <li><a href="<%= new_person_path %>">PROPUNE</a></li>
        <li><a href="<%= people_path %>">LIDERI</a></li>
        <li><a href="<%= terms_path %>">CONDITII</a></li>
        <li><a href="<%= about_path %>">NOI</a></li>
        <li><a href="<%= contact_path %>">CONTACT</a></li>
        <li>
          <% if user_signed_in? %>
              <%= link_to "log out", destroy_user_session_path, :method => :delete %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69744964-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/layouts/moderator.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
  <title>[moderator] propun&#9679;pe</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<p class="notice"><%= notice %></p>

<p class="alert"><%= alert %></p>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-primary btn-dropnav" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">moderator propun&#9679;pe</a>

      <div class="nav-collapse collapse">
        <ul class="nav pull-right">

          <li><a href="<%= moderator_index_path %>">PEOPLE</a></li>
          <li><a href="<%= openings_path %>">OPENINGS</a></li>
          <li><a href="<%= users_path %>">USERS</a></li>
          <li><a href="<%= people_path %>">to the site&raquo;</a></li>
          <li>
            <% if user_signed_in? %>
                <%= link_to "log out", destroy_user_session_path, :method => :delete %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="content">
  <div class="container">
    <div class="row">
      <div class="span12">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-69744964-1', 'auto');
    ga('send', 'pageview');

</script>
</body>
</html>